// <auto-generated />
using System;
using LTS_EDU_FINAL.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LTS_EDU_FINAL.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230720043801_update_v1")]
    partial class update_v1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LTS_EDU_FINAL.Entities.BaiViet", b =>
                {
                    b.Property<int>("BaiVietID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BaiVietID"));

                    b.Property<int>("ChuDeID")
                        .HasColumnType("int");

                    b.Property<string>("HinhAnh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NoiDung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NoiDungNgan")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int?>("TaiKhoanID")
                        .HasColumnType("int");

                    b.Property<string>("TenBaiViet")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TenTacGia")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("ThoiGianTao")
                        .HasColumnType("datetime2");

                    b.HasKey("BaiVietID");

                    b.HasIndex("ChuDeID");

                    b.HasIndex("TaiKhoanID");

                    b.ToTable("BaiViet");
                });

            modelBuilder.Entity("LTS_EDU_FINAL.Entities.ChuDe", b =>
                {
                    b.Property<int>("ChuDeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ChuDeID"));

                    b.Property<int?>("LoaiBaiVietID")
                        .HasColumnType("int");

                    b.Property<string>("NoiDung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenChuDe")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ChuDeID");

                    b.HasIndex("LoaiBaiVietID");

                    b.ToTable("ChuDe");
                });

            modelBuilder.Entity("LTS_EDU_FINAL.Entities.DangKyHoc", b =>
                {
                    b.Property<int>("DangKyHocID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DangKyHocID"));

                    b.Property<int?>("HocVienID")
                        .HasColumnType("int");

                    b.Property<int?>("KhoaHocID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayDangKy")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<int?>("TaiKhoanID")
                        .HasColumnType("int");

                    b.Property<int?>("TinhTrangHocID")
                        .HasColumnType("int");

                    b.HasKey("DangKyHocID");

                    b.HasIndex("HocVienID");

                    b.HasIndex("KhoaHocID");

                    b.HasIndex("TaiKhoanID");

                    b.HasIndex("TinhTrangHocID");

                    b.ToTable("DangKyHoc");
                });

            modelBuilder.Entity("LTS_EDU_FINAL.Entities.HocVien", b =>
                {
                    b.Property<int>("HocVienID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HocVienID"));

                    b.Property<string>("Email")
                        .HasMaxLength(40)
                        .HasColumnType("varchar");

                    b.Property<string>("HinhAnh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoTen")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("PhuongXa")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("QuanHuyen")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(11)
                        .HasColumnType("varchar");

                    b.Property<string>("SoNha")
                        .HasMaxLength(50)
                        .HasColumnType("varchar");

                    b.Property<string>("TinhThanh")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("HocVienID");

                    b.ToTable("HocVien");
                });

            modelBuilder.Entity("LTS_EDU_FINAL.Entities.KhoaHoc", b =>
                {
                    b.Property<int>("KhoaHocID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KhoaHocID"));

                    b.Property<string>("GioiThieu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HinhAnh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("HocPhi")
                        .HasColumnType("float");

                    b.Property<int>("LoaiKhoaHocID")
                        .HasColumnType("int");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SoHocVien")
                        .HasColumnType("int");

                    b.Property<int>("SoLuongMon")
                        .HasColumnType("int");

                    b.Property<string>("TenKhoaHoc")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("ThoiGianHoc")
                        .HasColumnType("int");

                    b.HasKey("KhoaHocID");

                    b.HasIndex("LoaiKhoaHocID");

                    b.ToTable("KhoaHoc");
                });

            modelBuilder.Entity("LTS_EDU_FINAL.Entities.LoaiBaiViet", b =>
                {
                    b.Property<int>("LoaiBaiVietID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LoaiBaiVietID"));

                    b.Property<string>("TenLoaiBaiViet")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("LoaiBaiVietID");

                    b.ToTable("LoaiBaiViet");
                });

            modelBuilder.Entity("LTS_EDU_FINAL.Entities.LoaiKhoaHoc", b =>
                {
                    b.Property<int>("LoaiKhoaHocID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LoaiKhoaHocID"));

                    b.Property<string>("TenLoaiKhoaHoc")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("LoaiKhoaHocID");

                    b.ToTable("LoaiKhoaHoc");
                });

            modelBuilder.Entity("LTS_EDU_FINAL.Entities.QuyenHan", b =>
                {
                    b.Property<int>("QuyenHanID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("QuyenHanID"));

                    b.Property<string>("TenQuyenHan")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("QuyenHanID");

                    b.ToTable("QuyenHan");
                });

            modelBuilder.Entity("LTS_EDU_FINAL.Entities.TaiKhoan", b =>
                {
                    b.Property<int>("TaiKhoanID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TaiKhoanID"));

                    b.Property<string>("MatKhau")
                        .HasMaxLength(50)
                        .HasColumnType("varchar");

                    b.Property<int?>("QuyenHanID")
                        .HasColumnType("int");

                    b.Property<string>("TenNguoiDung")
                        .HasMaxLength(50)
                        .HasColumnType("varchar");

                    b.Property<string>("TenTaiKhoan")
                        .HasMaxLength(50)
                        .HasColumnType("varchar");

                    b.HasKey("TaiKhoanID");

                    b.HasIndex("QuyenHanID");

                    b.ToTable("TaiKhoan");
                });

            modelBuilder.Entity("LTS_EDU_FINAL.Entities.TinhTrangHoc", b =>
                {
                    b.Property<int>("TinhTrangHocID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TinhTrangHocID"));

                    b.Property<string>("TenTinhTrang")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("TinhTrangHocID");

                    b.ToTable("TinhTrangHoc");
                });

            modelBuilder.Entity("LTS_EDU_FINAL.Entities.BaiViet", b =>
                {
                    b.HasOne("LTS_EDU_FINAL.Entities.ChuDe", "ChuDe")
                        .WithMany("BaiViet")
                        .HasForeignKey("ChuDeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LTS_EDU_FINAL.Entities.TaiKhoan", "TaiKhoan")
                        .WithMany("BaiViet")
                        .HasForeignKey("TaiKhoanID");

                    b.Navigation("ChuDe");

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("LTS_EDU_FINAL.Entities.ChuDe", b =>
                {
                    b.HasOne("LTS_EDU_FINAL.Entities.LoaiBaiViet", "LoaiBaiViet")
                        .WithMany("ChuDe")
                        .HasForeignKey("LoaiBaiVietID");

                    b.Navigation("LoaiBaiViet");
                });

            modelBuilder.Entity("LTS_EDU_FINAL.Entities.DangKyHoc", b =>
                {
                    b.HasOne("LTS_EDU_FINAL.Entities.HocVien", "HocVien")
                        .WithMany("DangKyHoc")
                        .HasForeignKey("HocVienID");

                    b.HasOne("LTS_EDU_FINAL.Entities.KhoaHoc", "KhoaHoc")
                        .WithMany("DangKyHoc")
                        .HasForeignKey("KhoaHocID");

                    b.HasOne("LTS_EDU_FINAL.Entities.TaiKhoan", "TaiKhoan")
                        .WithMany("DangKyHoc")
                        .HasForeignKey("TaiKhoanID");

                    b.HasOne("LTS_EDU_FINAL.Entities.TinhTrangHoc", "TinhTrangHoc")
                        .WithMany("DangKyHoc")
                        .HasForeignKey("TinhTrangHocID");

                    b.Navigation("HocVien");

                    b.Navigation("KhoaHoc");

                    b.Navigation("TaiKhoan");

                    b.Navigation("TinhTrangHoc");
                });

            modelBuilder.Entity("LTS_EDU_FINAL.Entities.KhoaHoc", b =>
                {
                    b.HasOne("LTS_EDU_FINAL.Entities.LoaiKhoaHoc", "LoaiKhoaHoc")
                        .WithMany("KhoaHoc")
                        .HasForeignKey("LoaiKhoaHocID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LoaiKhoaHoc");
                });

            modelBuilder.Entity("LTS_EDU_FINAL.Entities.TaiKhoan", b =>
                {
                    b.HasOne("LTS_EDU_FINAL.Entities.QuyenHan", "QuyenHan")
                        .WithMany("TaiKhoan")
                        .HasForeignKey("QuyenHanID");

                    b.Navigation("QuyenHan");
                });

            modelBuilder.Entity("LTS_EDU_FINAL.Entities.ChuDe", b =>
                {
                    b.Navigation("BaiViet");
                });

            modelBuilder.Entity("LTS_EDU_FINAL.Entities.HocVien", b =>
                {
                    b.Navigation("DangKyHoc");
                });

            modelBuilder.Entity("LTS_EDU_FINAL.Entities.KhoaHoc", b =>
                {
                    b.Navigation("DangKyHoc");
                });

            modelBuilder.Entity("LTS_EDU_FINAL.Entities.LoaiBaiViet", b =>
                {
                    b.Navigation("ChuDe");
                });

            modelBuilder.Entity("LTS_EDU_FINAL.Entities.LoaiKhoaHoc", b =>
                {
                    b.Navigation("KhoaHoc");
                });

            modelBuilder.Entity("LTS_EDU_FINAL.Entities.QuyenHan", b =>
                {
                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("LTS_EDU_FINAL.Entities.TaiKhoan", b =>
                {
                    b.Navigation("BaiViet");

                    b.Navigation("DangKyHoc");
                });

            modelBuilder.Entity("LTS_EDU_FINAL.Entities.TinhTrangHoc", b =>
                {
                    b.Navigation("DangKyHoc");
                });
#pragma warning restore 612, 618
        }
    }
}
